/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageServer_CONSTANTS_H
#define ImageServer_CONSTANTS_H

#include "ImageServer_types.h"



class ImageServerConstants {
 public:
  ImageServerConstants();

};

extern const ImageServerConstants g_ImageServer_constants;



#endif
