/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ImageServer_constants.h"



const ImageServerConstants g_ImageServer_constants;

ImageServerConstants::ImageServerConstants() {
}



