/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageServer_TYPES_H
#define ImageServer_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>





typedef struct _Pair__isset {
  _Pair__isset() : filename(false), result(false) {}
  bool filename;
  bool result;
} _Pair__isset;

class Pair {
 public:

  static const char* ascii_fingerprint; // = "C712EF0DA8599E55DF4D0F13415232EF";
  static const uint8_t binary_fingerprint[16]; // = {0xC7,0x12,0xEF,0x0D,0xA8,0x59,0x9E,0x55,0xDF,0x4D,0x0F,0x13,0x41,0x52,0x32,0xEF};

  Pair() : filename(), result(0) {
  }

  virtual ~Pair() throw() {}

  std::string filename;
  double result;

  _Pair__isset __isset;

  void __set_filename(const std::string& val) {
    filename = val;
  }

  void __set_result(const double val) {
    result = val;
  }

  bool operator == (const Pair & rhs) const
  {
    if (!(filename == rhs.filename))
      return false;
    if (!(result == rhs.result))
      return false;
    return true;
  }
  bool operator != (const Pair &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Pair & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Pair &a, Pair &b);



#endif
