//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./ImageServer_types');
//HELPER FUNCTIONS AND STRUCTURES

ImageServer_query_args = function(args) {
  this.filename = null;
  if (args) {
    if (args.filename !== undefined) {
      this.filename = args.filename;
    }
  }
};
ImageServer_query_args.prototype = {};
ImageServer_query_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.filename = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_query_args.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_query_args');
  if (this.filename !== null && this.filename !== undefined) {
    output.writeFieldBegin('filename', Thrift.Type.STRING, 1);
    output.writeString(this.filename);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServer_query_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ImageServer_query_result.prototype = {};
ImageServer_query_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString();
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_query_result.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_query_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServer_reload_func_args = function(args) {
  this.func_name = null;
  if (args) {
    if (args.func_name !== undefined) {
      this.func_name = args.func_name;
    }
  }
};
ImageServer_reload_func_args.prototype = {};
ImageServer_reload_func_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.func_name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_reload_func_args.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_reload_func_args');
  if (this.func_name !== null && this.func_name !== undefined) {
    output.writeFieldBegin('func_name', Thrift.Type.STRING, 1);
    output.writeString(this.func_name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServer_reload_func_result = function(args) {
};
ImageServer_reload_func_result.prototype = {};
ImageServer_reload_func_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_reload_func_result.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_reload_func_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServer_query_result_args = function(args) {
  this.filename = null;
  if (args) {
    if (args.filename !== undefined) {
      this.filename = args.filename;
    }
  }
};
ImageServer_query_result_args.prototype = {};
ImageServer_query_result_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.filename = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_query_result_args.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_query_result_args');
  if (this.filename !== null && this.filename !== undefined) {
    output.writeFieldBegin('filename', Thrift.Type.STRING, 1);
    output.writeString(this.filename);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServer_query_result_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ImageServer_query_result_result.prototype = {};
ImageServer_query_result_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = new ttypes.Pair();
          elem14.read(input);
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImageServer_query_result_result.prototype.write = function(output) {
  output.writeStructBegin('ImageServer_query_result_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        iter15.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImageServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
ImageServerClient.prototype = {};
ImageServerClient.prototype.query = function(filename, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_query(filename);
};

ImageServerClient.prototype.send_query = function(filename) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('query', Thrift.MessageType.CALL, this.seqid);
  var args = new ImageServer_query_args();
  args.filename = filename;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ImageServerClient.prototype.recv_query = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ImageServer_query_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('query failed: unknown result');
};
ImageServerClient.prototype.reload_func = function(func_name, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_reload_func(func_name);
};

ImageServerClient.prototype.send_reload_func = function(func_name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('reload_func', Thrift.MessageType.CALL, this.seqid);
  var args = new ImageServer_reload_func_args();
  args.func_name = func_name;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ImageServerClient.prototype.recv_reload_func = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ImageServer_reload_func_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ImageServerClient.prototype.query_result = function(filename, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_query_result(filename);
};

ImageServerClient.prototype.send_query_result = function(filename) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('query_result', Thrift.MessageType.CALL, this.seqid);
  var args = new ImageServer_query_result_args();
  args.filename = filename;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ImageServerClient.prototype.recv_query_result = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ImageServer_query_result_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('query_result failed: unknown result');
};
ImageServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ImageServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ImageServerProcessor.prototype.process_query = function(seqid, input, output) {
  var args = new ImageServer_query_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.query(args.filename, function (err, result) {
    var result = new ImageServer_query_result((err != null ? err : {success: result}));
    output.writeMessageBegin("query", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ImageServerProcessor.prototype.process_reload_func = function(seqid, input, output) {
  var args = new ImageServer_reload_func_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.reload_func(args.func_name, function (err, result) {
    var result = new ImageServer_reload_func_result((err != null ? err : {success: result}));
    output.writeMessageBegin("reload_func", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ImageServerProcessor.prototype.process_query_result = function(seqid, input, output) {
  var args = new ImageServer_query_result_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.query_result(args.filename, function (err, result) {
    var result = new ImageServer_query_result_result((err != null ? err : {success: result}));
    output.writeMessageBegin("query_result", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

